tap "lotyp/homebrew-formulae"

# core/dotfiles
brew "bats-core"
brew "coreutils"
brew "duti"
brew "lotyp/formulae/dockutil"
brew "nano"
brew "stow"
brew "tmux"
brew "topgrade"

# fs/network
brew "bat"
brew "croc"
brew "httpie"
brew "ssh-copy-id"
brew "tree"
brew "unar"
brew "wget"
brew "zoxide"

# search/grep/diff
brew "fd"
brew "fzf"
brew "gnu-sed"
brew "grep"
brew "jq"
brew "psgrep"
brew "ripgrep"
brew "the_silver_searcher"

# languages/tools
brew "shellcheck"

# media

# misc
